# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ known_as: 'Star Wars' }, { known_as: 'Lord of the Rings' }])
#   Character.create(known_as: 'Luke', movie: movies.first)
missing_person = Category.create(title: "Missing Person")
criminal = Category.create(title: "Criminal")
serial_killer = Category.create(title: "Serial Killer")
unsolved_mystery = Category.create(title: "Unsolved Mystery")
closed_case = Category.create(title: "Closed Case")



Case.create(known_as: "Joseph James DeAngelo", victim: false, bio: "The Golden State Killer is responsible for a series of burglaries, rapes and murders that took place across California in the 1970s and '80s. From 1976 to 1979, more than 40 rapes in northern California were attributed to an assailant called the East Area Rapist. In southern California between 1979 and 1986, a serial killer who was dubbed the Original Night Stalker took the lives of ten people. In 2001 DNA analysis revealed that these rapes and murders had been committed by the same perpetrator. In 2018 Joseph DeAngelo, a former police officer, was arrested and charged with 13 murders and other crimes linked to the GSK. In June 2020, DeAngelo pleaded guilty and was sentenced to life in prison without the possibility of parole." , solved: true, category: serial_killer)
Case.create(known_as: "Charles Manson", victim: false, bio:"Charles Manson was an American criminal who spearheaded a murderous campaign with his followers, the Manson Family cult, that would make him one of the most infamous figures in criminal history.Notorious for his connection to the brutal slayings of pregnant actress Sharon Tate and other Hollywood residents, Manson received the death penalty in 1971, a sentence that was commuted to life in prison the following year." , solved: true, category: criminal)
Case.create(known_as: "Junko Furuta", victim: true, bio:"Junko Furuta (古田 順子, Furuta Junko) was a Japanese high school student who was abducted, raped, tortured and murdered in the late 1980s. Her murder case was named (Concrete-encased high school girl murder case) (女子高生コンクリート詰め殺人事件), due to her body being discovered in a concrete drum. The abuse was mainly perpetrated by four teenage boys, Hiroshi Miyano, Jō Ogura, Shinji Minato, and Yasushi Watanabe.", solved: true, category: closed_case )
Case.create(known_as:"Zodiac Killer" , victim: false, bio:"The self-proclaimed Zodiac Killer was directly linked to at least five murders in Northern California in 1968 and 1969 and may have been responsible for more. He taunted police and made threats through letters sent to area newspapers from 1969 to 1974, before abruptly ceasing communication. Despite intensive investigations, no one was ever arrested for the crimes and the case remains open. The mystery surrounding the murders has been the subject of numerous books and movies, including director David Fincher's acclaimed 2007 feature Zodiac." , solved:false, category: serial_killer )
Case.create(known_as:"Hae Min Lee" , victim: true , bio: "Hae Min Lee (Korean: 이해민; October 15, 1980) was a Korean-American high school student who was last seen alive on January 13, 1999, in Baltimore County, Maryland. Her body was found four weeks later in Leakin Park; she had been killed by manual strangulation. Lee's ex-boyfriend, Adnan Masud Syed (born May 21, 1980), was convicted of first-degree murder and sentenced to life in prison plus thirty years.", solved: true, category: closed_case)
Case.create(known_as:"Elisa Lam", victim: true , bio:"The body of Elisa Lam, also known by her Cantonese name, Lam Ho Yi (藍可兒; April 30, 1991 – February 2013), a Canadian student at the University of British Columbia in Vancouver, was recovered from a water tank atop the Cecil Hotel in Downtown Los Angeles—at which she had been staying preceding her death—on February 19, 2013.2 She had been reported missing at the beginning of the month. A maintenance worker at the hotel discovered her body when investigating guest complaints of problems with the water supply and water pressure." , solved: false, category: unsolved_mystery )
Case.create(known_as: "JonBenét Ramsey", victim: true , bio: "JonBenét was an American child beauty queen who was killed at the age of six in her family's home in Boulder, Colorado. A lengthy handwritten ransom note was found in the home. Her father, John, found the girl's body in the basement of their house about seven hours after she had been reported missing. She had sustained a broken skull from a blow to the head and had been strangled; a garrote was found tied around her neck. The autopsy report stated that JonBenét's official cause of death was 'asphyxia by strangulation associated with craniocerebral trauma'.", solved: false, category: unsolved_mystery)
Case.create(known_as:"Henry Lee Lucas" , victim: false, bio: "Henry Lee Lucas (August 23, 1936 – March 12, 2001) was an American convicted serial killer whose crimes spanned from 1960 to 1983. He was convicted of murdering eleven people and condemned to death for the murder of Debra Jackson, although his sentence was commuted to life in prison in 1998. Lucas rose to infamy after confessing to more than 100 murders to the Texas Rangers and other law enforcement officials while in prison.", solved: true, category: serial_killer )
Case.create(known_as: "Joaquín (El Chapo) Guzmán", victim: false, bio: "Joaquín Archivaldo Guzmán Loera (born 4 April 1957), commonly known as 'El Chapo' ('Shorty' because of his 168 cm (5 ft 6 in) stature, is a Mexican drug lord and former leader of the Sinaloa Cartel, an international crime syndicate. He is considered to have been the most powerful drug trafficker in the world", solved: true, category: criminal)
Case.create(known_as:"Pablo Escobar" , victim: false, bio:"Pablo Emilio Escobar Gaviria (1 December 1949 – 2 December 1993) was a Colombian drug lord and narcoterrorist who was the founder and sole leader of the Medellín Cartel. Dubbed 'The King of Cocaine,' Escobar is the wealthiest criminal in history, having amassed an estimated net worth of US$30 billion by the time of his death—equivalent to $59 billion as of 2019—while his drug cartel monopolized the cocaine trade into the United States in the 1980s and early 1990s." , solved: true, category: criminal)
Case.create(known_as: "John Wayne Gacy", victim:false, bio: "John Wayne Gacy was an American serial killer and rapist who took the lives of at least 33 young males in Cook County, Illinois, burying most under his house. Other bodies were recovered from the nearby Des Plaines River. Sometimes known as the Killer Clown for his habit of dressing in a clown costume and makeup, Gacy had an abusive childhood and struggled with his homosexuality. After being convicted of sexual assault in 1968, Gacy's murders were discovered. " , solved: true, category: serial_killer)
Case.create(known_as: "Ted Bundy", victim: false , bio:"Theodore Robert Bundy (born Cowell; November 24, 1946 – January 24, 1989) was an American serial killer who kidnapped, raped, and murdered numerous young women and girls during the 1970s and possibly earlier. After more than a decade of denials, before his execution in 1989 he confessed to 30 homicides that he committed in seven states between 1974 and 1978. The true number of victims is believed to be higher. Bundy was regarded as handsome and charismatic, traits that he exploited to win the trust of victims and society. He would typically approach his victims in public places, feigning injury or disability, or impersonating an authority figure, before knocking them unconscious and taking them to secluded locations to rape and strangle them" , solved: true, category: serial_killer )
Case.create(known_as: "Al Capon ", victim: false, bio: "Al Capone, byname of Alphonse Capone, also called Scarface, (born January 17, 1899, Brooklyn, New York, U.S.—died January 25, 1947, Palm Island, Miami Beach, Florida), American Prohibition-era gangster, who dominated organized crime in Chicago from 1925 to 1931 and became perhaps the most famous gangster in the United States.", solved: true, category: criminal)
Case.create(known_as:"Jack The Ripper" , victim: false, bio: "Jack the Ripper was an English serial killer. Between August and November 1888, he murdered at least five women—all prostitutes—in or near the Whitechapel district of London's East End. Jack the Ripper was never identified or arrested.", solved:false, category: serial_killer )
Case.create(known_as:"Jeffrey Dahmer" , victim: false, bio: "Jeffrey Lionel Dahmer (/ˈdɑːmər/; May 21, 1960 – November 28, 1994), also known as the Milwaukee Cannibal or the Milwaukee Monster, was a convicted American serial killer and sex offender who committed the murder and dismemberment of 17 men and boys from 1978 to 1991. Many of his later murders involved necrophilia,cannibalism, and the permanent preservation of body parts—typically all or part of the skeleton.Although he was diagnosed with borderline personality disorder,schizotypal personality disorder, and a psychotic disorder, Dahmer was found to be legally sane at his trial.", solved: true, category: serial_killer)
Case.create(known_as:"Madeleine McCann" , victim: true, bio:"Madeleine Beth McCann (born 12 May 2003)  was on holiday from the UK with her parents, Kate and Gerry McCann; her two-year-old twin siblings; and a group of family friends and their children. She and the twins had been left asleep at 20:30 in the ground-floor apartment, while the McCanns and friends dined in a restaurant 55 metres (180 ft) away. The parents checked on the children throughout the evening, until Kate discovered she was missing at 22:00. Over the following weeks, particularly after misinterpreting a British DNA analysis, the Portuguese police came to believe that Madeleine had died in an accident in the apartment and that her parents had covered it up." , solved: false, category:missing_person)
Case.create(known_as: "Caylee Anthony", victim: true, bio: "Caylee Marie Anthony (August 9, 2005 – 2008) was an American girl who lived in Orlando, Florida, with her mother, Casey Marie Anthony (born March 19, 1986),and her maternal grandparents, George and Cindy Anthony. On July 15, 2008, she was reported missing in a 9-1-1 call made by Cindy, who said she had not seen Caylee for 31 days and that Casey's car smelled like a dead body had been inside it. Cindy said Casey had given varied explanations as to Caylee's whereabouts before finally telling her that she had not seen Caylee for weeks. Casey lied to detectives, telling them Caylee had been kidnapped by a nanny on June 9, and that she had been trying to find her, too frightened to alert the authorities.", solved: false, category: unsolved_mystery)
Case.create(known_as: "David Berkowitz", victim: false, bio: "David Richard Berkowitz (born Richard David Falco, June 1, 1953), also self-proclaimed with the name Son of Sam and christened by the media as .44 Caliber Killer due to the weapon he used, is an American serial killer who pled guilty to eight separate shooting attacks that began in New York City during the summer of 1976." , solved:true, category: serial_killer)
Case.create(known_as: "Rosemary West", victim: false, bio:"Rosemary Pauline West (née Letts; born 29 November 1953), or Rose West, is an English serial killer who collaborated with her husband, Fred West, in the torture and murder of at least nine young women between 1973 and 1987; she was also judged to have murdered her eight-year-old stepdaughter, Charmaine, in 1971. The majority of these murders took place at the Wests' residence at 25 Cromwell Street, Gloucester. " , solved: true, category: serial_killer)
Case.create(known_as: "Richard Ramirez", victim: false, bio: "Ricardo Leyva Muñoz Ramírez (February 29, 1960 – June 7, 2013), known as Richard Ramirez, was an American serial killer, serial rapist, kidnapper, pedophile, and burglar. His highly publicized home invasion and murder crime spree terrorized the residents of the Greater Los Angeles area and later the residents of the San Francisco Bay Area from June 1984 until August 1985. Prior to his capture, Ramirez was dubbed the 'Valley Intruder' (as his attacks were first clustered in the San Gabriel Valley) and the 'Night Stalker' by the news media. Ramírez used a wide variety of weapons, including handguns, knives, a machete, a tire iron, and a hammer, as well as Satanic imagery. Ramirez never expressed any remorse for his crimes." , solved: true, category: serial_killer)



